# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore -c Release

    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal --logger:"xunit;LogFilePath=test-results.xml"

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |        
          ./Tests/TrinityContinuum.ApiTests/test-results.xml
          ./Tests/TrinityContinuum.Tests/test-results.xml
          ./Tests/TrinityContinuum.UITests/test-results.xml

    - name: Upload API Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: api-package # optional, default is artifact
        path: ./Source/Backend/TrinityContinuum.Server/bin/Release/net9.0/**
        retention-days: 2 # optional
        overwrite: true # optional, default is false

    - name: Upload WebApp Artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: app-package # optional, default is artifact
        path: ./Source/Frontend/TrinityContinuum.WebApp/bin/Release/net9.0/**
        retention-days: 2 # optional
        overwrite: true # optional, default is false
